# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme


# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "defaut", "dirt", "neon", "mint", "plum", "sunrise"


# Site Settings
# locale                   : "fr"
## Replaced by site.lang
title: Blog Vaniila
email:
description: "Blog Vaniila"
url :
logo :  /assets/images/Logo_blog_VANIILA.png
google_site_verification:
twitter_username: CATIE_AQ
github_username: CATIE_AQ
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-multiple-languages-plugin

languages: ["fr", "en"]

# exclude_from_localizations: ["assets", "_sass"]

# _pages/toto.md is in french (default locale) --- >  _i18n/en/_pages/toto.md  is in english
# default_locale_in_subfolder: false

## WARNING: author content uses the locale -> please look at it
author:
  name   : "BLOG VANIILA"
  avatar : "/assets/images/Logo_blog_VANIILA.png"
  bio              : "Plus de détails nous concernant dans la page *A propos*."
  location         : "Bordeaux"

## Labels are translated in links 
  links:
    - label: platform
      icon: "fas fa-fw fa-desktop"    
      url: "https://www.vaniila.ai/"
    - label: catie
      icon: "fas fa-fw fa-globe" 
      url: "https://www.catie.fr/"
    - label: email
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:contact@vaniila.ai 
    - label: twitter
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/CATIE_AQ"
    - label: linkedin
      icon: "fab fa-fw fa-linkedin"      
      url: "https://www.linkedin.com/company/catie-aq/"
    - label: github
      icon: "fab fa-fw fa-github"
      url: "https://github.com/catie-aq"
    - label: hugging_face
      icon:      
      url: "https://huggingface.co/CATIE-AQ"   
      
# Site Footer
footer:
  links:
    - label: platform
      icon: "fas fa-fw fa-desktop"    
      url: "https://www.vaniila.ai/"
    - label: catie
      icon: "fas fa-fw fa-globe" 
      url: "https://www.catie.fr/"
    - label: email
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:contact@vaniila.ai 
    - label: twitter
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/CATIE_AQ"
    - label: linkedin
      icon: "fab fa-fw fa-linkedin"      
      url: "https://www.linkedin.com/company/catie-aq/"
    - label: github
      icon: "fab fa-fw fa-github"
      url: "https://github.com/catie-aq"
    - label: hugging_face
      icon:      
      url: "https://huggingface.co/CATIE-AQ"  


defaults:
  # _posts

## Cette partie n'est sûrement plus utilisée, car les pages sont déclarées explicitement maintenant.
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

mathjax: true
